Project-Aurora/Profiles/Overlays/VolumeOverlay/Event_VolumeOverlay.cs, Project-Aurora/Profiles/Overlays/VolumeOverlay/VolumeOverlaySettings.cs, Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Settings/Control_Settings.xaml.cs
I added an option to black out keys under the volume overlay area before applying the volume overlay effect itself. This way it's better seen on backgrounds where the effect would otherwise blend in, such as animated rainbow or solid green color.
It's working, but inefficiently using a gradient EffectLayer just for a solid black background, I basically just copied the procedure from the volume overlay itself, because I didn't delve into the code much. So maybe it's more appropriate to consider this as an feature request and change this PR to a proper implementation, with different variable nomenclature according to the codestyle etc.
=> Dim background option in Volume overlay effect

Project-Aurora/EffectsEngine/EffectLayer.cs
For example we have 5 keys for displaying percent effect. 
They have indexes 0-4. 
keys.Count() is 5.
Than for 100% we are taking color `(float)i / (float)(keys.Count()`  = 4/5 = 0.8 in spectrum.
Instead we should take `(float)i / (float)(keys.Count() - 1)` = 4/4 = 1 in spectrum
=> Small fix EffectLayer.PercentEffect didn't use whole color spectrum.

Project-Aurora/Profiles/Aurora Wrapper/GameEvent_Aurora_Wrapper.cs, Project-Aurora/Profiles/Blade and Soul/BnSSettings.cs, Project-Aurora/Profiles/Blade and Soul/Control_BnS.xaml, Project-Aurora/Profiles/Blade and Soul/Control_BnS.xaml.cs, Project-Aurora/Profiles/Blade and Soul/GameEvent_BnS.cs, Project-Aurora/Profiles/Overwatch/Control_Overwatch.xaml, Project-Aurora/Profiles/Overwatch/Control_Overwatch.xaml.cs, Project-Aurora/Profiles/Overwatch/GameEvent_Overwatch.cs, Project-Aurora/Profiles/Overwatch/OverwatchSettings.cs, Project-Aurora/Profiles/Worms_WMD/Control_WormsWMD.xaml, Project-Aurora/Profiles/Worms_WMD/Control_WormsWMD.xaml.cs, Project-Aurora/Profiles/Worms_WMD/GameEvent_WormsWMD.cs, Project-Aurora/Profiles/Worms_WMD/WormsWMDSettings.cs
I have added two additional methods to calculate a brighter color for the Razer Wrapper.
- Simple: A simple multiplication with some overflow detection, and
- Gamma: An implementation of an image gamma correction.
The first one isn't very special, but some people might use it.
The second is pretty good a brighten very dark colors, but makes light colors a bit gray.
In addition, I removed the initial_factor because it wasn't needed.
=> New Color Enhancement Method with HSV

Project-Aurora/GameEventHandler.cs
#430 
#424
The old Process Detection was using the ProcessModule to get the FilePath. This could cause problems, because games, compiled in x64 can't be accessed in this way.
I changed the detection to only use WINAPI calls, so Aurora don't need to access the Process directly anymore.
I only needed to change the GetActiveWindowsProcessname() Method in GameEventHandler.cs
I'am using the `GetProcessHandleFromHwnd()` call to get the process handle from the foreground window, then i get the full path with the `GetModuleFileNameEx()` call.
No Exception handling is needed, the returned fileName will be an empty string when no foreground window exists.
=> Changed the Process detection to WINAPI only.

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Utils/ActiveProcessMonitor.cs
- Some apps and games (like Blade & Soul) runs with admin rights (i.e. evevated). Built in ```Process.MainModule.FileName``` uses old function that throws access denied exception when target process is elevated, despite of calling process is elevated or not. 
In Vista and above exists a new win function for this task. I've changed code to use it. 
[Here is an article about this bug.](http://www.aboutmycode.com/net-framework/how-to-get-elevated-process-path-in-net/)
- Fix inconsistent lower-casing when comparing process names. In ```LightingStateManager``` ```RegisterEvent()``` used ```ToLower()``` while comparing in ```Update()``` was using ```ToLowerInvariant()```.
=> Getting process names fixes

Project-Aurora/Project-Aurora/kb_layouts/Extra Features/corsair_k95_platinum_left_features.json
- Small fix in the json for K95 Platinum, some "G keys" at the left were no lighting up at all.
=> Fix G keys mapping for Corsair K95 Platinum keyboard

Project-Aurora/Project-Aurora/Profiles/DyingLight/Control_DyingLight.xaml.cs, Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Properties/Resources.Designer.cs, Project-Aurora/Project-Aurora/Properties/Resources.resx, Project-Aurora/Project-Aurora/Utils/JSonUtils.cs
The buttons were patching and unpatching shador of mordor due to incorrect steam appID's.
=> Fixed Dying Light Install and uninstall wrapper patch buttons

Project-Aurora/Project-Aurora/kb_layouts/Extra Features/razer_blackwidow_features.json
See [here](https://www.razerzone.com/gaming-keyboards-keypads/refurbished-razer-blackwidow-chroma-v1).
=> Razor macro key naming fixed

Project-Aurora/Project-Aurora/Devices/DeviceManager.cs
Check if worker is busy before doing another work if for some reason worker sets newFrame to true without finishing last frame.
Fixes #1061 
Fixes #1046 
- Fix for worker throwing exception.
- N/A
=> Fix for issue #1046 and #1061

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/ConditionalLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_ConditionalLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_ConditionalLayer.xaml.cs
Adds a simple conditional layer which allows for key colors to be set based on a boolean value read from a game state integration.
=> Simple Conditional Layer

Project-Aurora/Project-Aurora/Controls/Control_Keybind.xaml.cs, Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs
Improved the logic for keybind switching so that it behaves more reliably when multiple profiles have the same keybind (#1077).
Currently it cycles through profiles in the order they were created, so some way of changing the order should probably be added in future though this works for now.
=> Improved Profile Keybind Switching

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/Control_TimerLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_TimerLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/TimerLayerHandler.cs
Adds a layer whose sequence is lit in a single color. Then when a keybind is pressed (can be separate from the seqence) the sequence changes to another color for a set duration. After the duration, the keys return to their original color.
Can also be set so that the keys fade back to their original colour instead of abruptly changing.
Multiple "repeat actions" are available to customise what happens if one or more of the keybinds are pressed again while the timer is active:
- Reset (Default) - Restarts the timer when the key is pressed.
- Extend - Adds another duration onto the end of the existing one (so multiple presses stack).
- Ignore - Ignores a keypress while timer is active, and simply continues the existing one.
Thanks to _amahlaka97_ on Discord for the suggestion!
=> Timed Key Layer

Project-Aurora/Project-Aurora/Profiles/Application.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_ScriptLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_ScriptLayer.xaml.cs
Cleaned up the interface for the script layer and added the ability to reload scripts.
Previously, Aurora would need to be restarted before script changes or new scripts would be recognised, which was a pain if you were actively developing and testing a script. With this change it is much quicker :)
=> Minor script layer improvements

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/Control_ToolbarLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_ToolbarLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/ToolbarLayerHandler.cs, Project-Aurora/Project-Aurora/Utils/InputEvents.cs, Project-Aurora/Project-Aurora/Utils/MouseUtils.cs
This allows for layers such as a layer whose highlighted keys depends on the scroll position (consider the toolbar at the bottom of games such as Factorio or Minecraft).
EDIT: Added a ToolbarLayer that utilised the mouse scroll event. This layer was as suggested by amahlaka97 on Discord and the scroll improvement was suggested by DrMeteor/diogotr7. When one of the keys in the sequence it uses is pressed, that key becomes "active". When another key is pressed, that key becomes active instead and resets the others to their default state. It's sort of like a radio button but for the keys on the keyboard. An option is provided that allows the mouse scroll wheel to be used to scroll up and down the active key.
=> Added mouse events to Global.InputEvents

Project-Aurora/Aurora-RazerLEDWrapper/dllmain.cpp
Adds null check when handling effects in Razer wrapper. This fixes Dead Cells crash and adds it support in Aurora and possibly other games.
=> Fix for Dead Cells crash and possibly other games

Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml.cs, Project-Aurora/Project-Aurora/Settings/Window_ProcessSelection.xaml, Project-Aurora/Project-Aurora/Settings/Window_ProcessSelection.xaml.cs
Replaced existing dropdown containing running processes with a sorted, searchable list (with icons!) in a dedicated dialog window. Users can also browse to executable files without needing to run them first.
Resolves issue #1259.
=> Added a dedicated dialog instead of drop down for excluding processes.

Project-Aurora/Project-Aurora/Controls/Control_VariableRegistryItem.xaml.cs
Adds missing support for `float` and `double` types for the Control_VariableRegistryItem (used in script layer).
=> Added float and double types for script layers

Project-Aurora/Project-Aurora/Profiles/GameState.cs
Added `SystemVolume` and `SystemVolumeIsMuted` properties to `LocalPCInfo` state.
`SystemVolume` is a float between 0 - 100 and represents the current system volume as set by the speaker tray icon, designed to be used with the percent layers to show a volume bar.
`SystemVolumeIsMuted` is a (self-explanatory) boolean and can be used with the conditional to highlight when the master system volume is muted.
=> Added SystemVolume and SystemVolumeIsMuted properties to LocalPCInfo

Project-Aurora/Project-Aurora/Settings/Layers/EqualizerLayerHandler.cs
Fixed visualizer layer to be able to use 2 channels if they are present. If so, takes the largest value from the left and right channel and adds to the aggregator. Previously this would only add the left channel, meaning that if there was some audio only in the right channel it would not be displayed on the visualizer.
Resolves issue #1281.
=> Fixed Visualizer Layer to use 2 channels

Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFilledRectangle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationRectangle.cs
Made the rectangle and filled rectangle rotate about their origins.
This fixes weird behaviour when changing width/height of rotated rectangles. This may also affect any user-made animations but will be minor and easy to fix.
=> Animation rectangles use origin

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/ComparisonLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_ComparisonLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_ComparisonLayer.xaml.cs
Added a comparison layer that can be used to compare two numerical values and change the (solid) color of a key sequence based on the result.
Each operand can either be a path to a game state variable (such as ammo counter, health, speed, etc) or a raw number. The operator can be equals (=), not equal (≠), less than (<), less than or equal (≤), greater than (>) or greater than or equal (≥).
---
Here is an example of it using the Euro Truck Simulator 2 game state to show a red warning if the Engine RPM goes above 80%.
=> Added comparison layer

Project-Aurora/Project-Aurora/Controls/KeySequence.xaml, Project-Aurora/Project-Aurora/Controls/KeySequence.xaml.cs, Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_WrapperLightsLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_WrapperLightsLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/WrapperLightsLayerHandler.cs
Adds an option to the wrapper layer to allow keys to be cloned. This involves taking the color from a source key and applying it to one or more destination keys. There can be multiple source keys each with their own set of destination keys.
Also quick fix for the "Allow Aurora wrappers to take priority over desktop profile" checkbox so it works as intended.
Thanks to @Gurjot95 for the help with this!
=> Wrapper layer key cloning

Project-Aurora/Project-Aurora/ConfigUI.xaml.cs, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml.cs, Project-Aurora/Project-Aurora/Settings/Window_ProcessSelection.xaml, Project-Aurora/Project-Aurora/Settings/Window_ProcessSelection.xaml.cs
Made the add profile button use the process picker selection dialog.
Process selection dialog browse dialog now has a `*.*` filter to allow non-exes to be added (resolves #1339). Has been tested with Red Alert 3 Uprising's `.game` file (does not use `.exe`).
Process selection dialog now also has the option to change okay button label, can return full path of selected process and can require file validation on the text from the browse for process tab text box.
=> Made "Add profile" use Process Picker

Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationCircle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationEllipse.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFill.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFilledCircle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFilledGradientRectangle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFilledRectangle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationFrame.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationGradientCircle.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationLine.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationLines.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationManualColorFrame.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationMix.cs, Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationRectangle.cs, Project-Aurora/Project-Aurora/Settings/Layers/AnimationLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/ComparisonLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_AnimationLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_AnimationLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_ComparisonLayer.xaml.cs, Project-Aurora/Project-Aurora/Utils/GameStateUtils.cs
Added a set of trigger options to the animation layer to allow user's to trigger an animation when a particular value in the game state changes. For example, the keyboard could flash red whenever the player takes damage. Original functionality is still available when the trigger is set to "Always On" (default).
- The possible trigger values are:
- Always on (Same as old animation layer functionality)
- On value increase
- On value decrease
- On value change
- On boolean become true (Plays once when the value changes from false to true)
- On boolean become false
- While boolean true (Plays continuously while the value is true)
- On key pressed (Plays once when the key is pressed)
- On key released
- While key held (Plays continuously while the key is held down)
- For the value triggers, …
=> Add Animation Layer Triggers

Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml.cs, Project-Aurora/Project-Aurora/Settings/Window_GSIHttpDebug.xaml, Project-Aurora/Project-Aurora/Settings/Window_GSIHttpDebug.xaml.cs
Adds a button to _Settings_ > _Debug_ to open a window that shows the (formatted/indented) JSON that the network listener receives when waiting for GSI HTTP POST requests.
Useful for debug purposes when developing GSI mods.
=> Added HTTP GSI request viewer (for debug)

Project-Aurora/Project-Aurora/ConfigUI.xaml, Project-Aurora/Project-Aurora/Settings/Layers/AnimationLayerHandler.cs
* Changes logic so that the key is always recorded during the key press events (previously would only record when translating was set to true).
* This fixes issue where holding a key during the "While key held" setting, with translating off would cause the animation to immediately restart.
* Also fixes issue where "Terminate animation immediately" would not work if translating was off.
* Increases the size of the default unmaximised Aurora window to show all of the animation layer properties without needing to be resized.
=> Minor Animation Layer Bugfix

Project-Aurora/Project-Aurora/Profiles/Application.cs, Project-Aurora/Project-Aurora/Profiles/Generic_Application/GenericApplication.cs
"This minor change fixes errors when creating/importing profiles with the same name as existing ones. File name collisions can cause profile data to be overritten and also caused the weird behaviour that sometimes occured with the profile selection list not being able to select items.
Fixed by replacing GetValidFilename with a new method GetUnusedFilename in some places, which will find the next available file name based on the given profile name. E.G for a profile "test" it will find the first free file from: "test.json", "test-1.json", "test-2.json" etc.
Thanks to gitmacer for the bug testing and finding it was due to file names."
=> "Fixed file name collisions that can cause profile data to be overritten." by @Wibble199

Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml.cs
This minor change adds a numeric stepper allowing the user to set the delay of the Aurora startup task, without needing to go to the Task Scheduler. Delaying Aurora's startup fixes a relatively common issue some users have where Aurora starts before the vendor software and doesn't initalise the devices automatically.
=> Add startup delay to Aurora settings

Project-Aurora/Project-Aurora/Profiles/RocketLeague/Layers/Control_RocketLeagueBackgroundLayer.xaml.cs
- The Rocket League Background Layer was incorrectly loading the wrong saved property on ShowEnemyExplosion, using the value of ShowGoalExplosion, overriding it on every load.
=> Fixed RL Background Layer options being overriden on load

Project-Aurora/Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/InteractiveLayerHandler.cs
The interactive layer has a `pressBuffer` constant set to `300`. This is the minimum time between the effects for the same key. For example, if a key is pressed it will animate. If pressed again 200ms later, it will not. If pressed again 200ms later, it will etc.
This PR adds a checkbox option to the interactive layer to disable this functionality, allowing rapid keypresses to keep triggering an effect. By default, this option is enabled, so as to behave as it used to.
Resolves #1448
=> Add option to toggle buffer with Interactive Layer

AuroraArduino/AuroraArduino.ino, README.md
This PR introduces a microcontroller compatible implementation of the already implemented LED driver software for the Raspberry Pi.
It allows the user to use a microcontroller (in my case NodeMCUs ESP8266) to receive, deserialize and update the LED status instead of a Raspberry Pi, which is more expensive, bigger and consumes more power.
Since the ESP8266 is WiFi capable this can be done completely wireless.
This new approach is entirely backward compatible with the already existing interface to Aurora which is used to transmit the lighting updates to the Raspberry Pi.
Fixes https://github.com/antonpup/Aurora/issues/473
Fixes https://github.com/antonpup/Aurora/issues/996
* Added …
=> Add NodeMCU ESP8266 microcontroller support for driving external LED strips

Project-Aurora/Project-Aurora/Pointers/ResidentEvil2.json
Resident Evil 2 (2019) pointers updated to newest version. Works as intended.
=> Updated RE2 (2019) pointers

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/BinaryCounterLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_BinaryCounterLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_BinaryCounterLayer.xaml.cs
This PR adds a new layer type: the binary counter layer.
It accepts a state variable and displays it on the given key sequence in binary form, with the first key in the list representing the right-most bit, the second key representing the second right-most bit, etc.
The value can also be override through the overrides system, allowing for displaying the results of override operations.
This is related to enhancement #1617.
---
In this example Binary clock, two of these layers have been used with the overrides system to show `CurrentSecond / 10` (in green, showing the units) and `CurrentSecond % 10` (in blue, showing the tens), as a true binary clock would.
=> Binary Counter Layer

Project-Aurora/Project-Aurora/Profiles/Dota 2/Layers/Dota2AbilityLayerHandler.cs
New High five ability and the seasonal abilites break the current ability layer, causing the whole profile to be black.
This skips any ability that isn't relevant (no cooldown).
=> Fixes dota2 ability layer not handling seasonal abilities

Project-Aurora/Project-Aurora/Profiles/GameState.cs, Project-Aurora/Project-Aurora/Settings/Configuration.cs, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml
Adds an option to the settings to disable the microphone level gamestate (and thus the Windows 10 "Aurora is using your microphone" notification). This will give people the peace of mind that Aurora isn't spying on them.
It may be possible that Aurora is capable of getting the data without triggering the microphone in it's current state, but I _think_ this is dependent on whether the mic is in use already. Either way, this resolves the microphone notification issue.
=> Audio capture checkbox

Project-Aurora/Project-Aurora/Profiles/Minecraft/GSI/Nodes/GameNode.cs, Project-Aurora/Project-Aurora/Profiles/Minecraft/GSI/Nodes/WorldNode.cs, Project-Aurora/Project-Aurora/Profiles/Minecraft/MinecraftProfile.cs
Adds new boolean variable that lets the user make the keyboard a solid color when typing a message, and added overrides for the background colors to fit in better with the vanilla dimensions. Of course users can add more overrides to any modded dimensions provided they know their id's.
Version 0.2.1 of the GSI mod is needed, and i've updated all the mods to have this. I've also published the updated mods to curseforge and gitlab.
=> Added new minecraft gsi variable dimensionID and chatguiopen

Project-Aurora/Project-Aurora/EffectsEngine/Animations/AnimationMix.cs
Currently `AnimationMix.GetDuration()` simply returns the duration of the longest `AnimationTrack` without accounting for track shifts.
This PR fixes this issue.
=> Fixed AnimationMix.GetDuration not returning a correct duration

Project-Aurora/Project-Aurora/EffectsEngine/EffectLayer.cs
- Enable blink Background if you are using a freestyle sellection
- 
- 
**Known issues:/To do:**
- Blink will work different depending if you use freestyle or keylist
=> (Percent Effect Layer) Add support for blink background when freeform is used

Project-Aurora/Project-Aurora/Profiles/LeagueOfLegends/Control_LoL.xaml.cs
Was failing silently if something went wrong, should now show a message box if it doesn't find the path and log if it fails to write the dll or something similar.
=> Fixed League of legends patch button

Project-Aurora/Project-Aurora/Settings/Layers/RazerLayerHandler.cs
key cloning wasnt working if the destination key had a higher devicekeys value than the origin because it was being overwritten later in the loop.
=> Fixed key cloning in razer chroma layer

Project-Aurora/Project-Aurora/Profiles/Move or Die/Control_MoD.xaml, Project-Aurora/Project-Aurora/Profiles/Move or Die/Control_MoD.xaml.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Utils/FileUtils.cs
- Change patch folder to Move or Die\Love\win
- Add ability to Disable/rename MoDs Corsair sdk because icue will prefere the newest connection and you cannot disable Apps in iCUE.
- 
- 
-
=> Change move or die Patch folder and function to disable Corsair implementation from the Game

Project-Aurora/Project-Aurora/ConfigUI.xaml.cs
Fixes occasional crash when deleting a custom profile.
This sometimes occured when the previous profile in the list was hidden and the user had not shown the hidden profiles. Aurora would then try to select the item before the one deleted and try to get the average color of the profile's icon and crash (perhaps since the resource hadn't been loaded or something?).
Now, when deleting a profile, it will select the next non-hidden profile.
=> Fix uncommon crash when deleting custom profile

Project-Aurora/Project-Aurora/Profiles/AutoJsonNode.cs
Fixed AutoJsonNode crash when it encounters a node with no fields.
=> Fix AutoJsonNode crash on node without fields

Project-Aurora/Project-Aurora/EffectsEngine/EffectLayer.cs, Project-Aurora/Project-Aurora/EffectsEngine/SegmentedRadialBrushFactory.cs, Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/Control_ParticleLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_RadialLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_RadialLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/RadialLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/SimpleParticleLayerHandler.cs, Project-Aurora/Project-Aurora/Utils/BrushUtils.cs
This PR adds a radial layer which allows the user to create a gradient around a point. This gradient can be animated if desired.
This has been implemented as a standalone brush factory (uses a texture brush) for any other layers that wish to use it.
Note this PR depends on #1842.
=> Segmented radial brush

Project-Aurora/Project-Aurora/Settings/Layers/EqualizerLayerHandler.cs
increases the resolution of the rectangle to fix weird lines in waveform
increased multiplier of the waveform to better align it with the power bars view type (assuming same "sensitivity")
changed fft function to be more reactive to audio change.
=> audio visualizer layer tweaks

Project-Aurora/Project-Aurora/Profiles/Node.cs
Does what the PR title says.
Just a simple thing that should be allowed this will help making plugins in specific ways easier.
=> Allow Node funcs to be accessed in outside plugins.

Project-Aurora/Project-Aurora/Devices/Asus/AsusDevice.cs, Project-Aurora/Project-Aurora/Devices/Asus/AsusHandler.cs, Project-Aurora/Project-Aurora/Devices/Asus/Config/AsusConfigWindow.xaml.cs
This pr fix the following issues:
The the problem is that when the first time asusHandler constructor was called the varRegistry is not yet registered so it going to throw exception which i think not intended behavior
The other problem the registered varRegistry name is not equals with get part
=> Fix Asus unsupported sdk version handling

Project-Aurora/Project-Aurora/Controls/KeySequence.xaml, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Number/Number_Maths.cs, Project-Aurora/Project-Aurora/Settings/ProfileImporter.cs
- Fix profile importer not importing overlayers.
- Fix the arithmetic comparison evaluatable not maintaining the operator when it is cloned.
=> Misc. fixes

Project-Aurora/Project-Aurora/Profiles/LocalPCInformation.cs, Project-Aurora/Project-Aurora/Settings/Configuration.cs, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/AmbilightLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_EqualizerLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/EqualizerLayerHandler.cs, Project-Aurora/Project-Aurora/Utils/HardwareMonitor.cs
and redesigned the audio visualizer layer UI
=> Fixed a few small things

Project-Aurora/Project-Aurora/Profiles/Desktop/Event_Desktop.cs
Fixed an issue where overlay layers on the desktop profile were being updated twice in a single frame when either the Aurora window was not focused or the desktop was being previewed while "Show Overlays in Application Preview" is checked.
This was particularly noticable with the particle layer. Creating one as a normal layer and one as an overlay demonstrates the issue.
=> Fixed issue where desktop overlays are rendered multiple times.

Project-Aurora/Project-Aurora/Settings/Configuration.cs, Project-Aurora/Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Project-Aurora/Utils/HardwareMonitor.cs
should make the transitions easier to look at.
=> Added smoothing to the hw monitor values

Project-Aurora/Project-Aurora/Profiles/Discord/GSI/AuroraGSI.plugin.js
- Add all changes made so far in plugin so it doesn't have to be updated from repo...
- Allow tracking mute/deafen statuses outside voice channel
- Fix unread status for Enhanced Discord users
- Fix self-updating loop
- Fix `being_called` boolean so it's now usable
=> Reflect all changes made in BetterDiscord plugin

Project-Aurora/Project-Aurora/Settings/Configuration.cs, Project-Aurora/Project-Aurora/Utils/HardwareMonitor.cs
had one queue per hardware, which makes no sense. now has one queue per *sensor*, having a dictionary per hardware to store these queues.
also makes overlays render in preview by default.
=> Fixed hardware monitor value smoothing
