antonpup/Aurora

.gitignore, Project-Aurora/GameEventHandler.cs, Project-Aurora/Profiles/Desktop/Event_Desktop.cs, Project-Aurora/Project-Aurora.csproj
This will resolve #91 I believe. I have tested with my setup mentioned above and on Overwatch/desktop mode. I will need to download CS:GO again and made sure its effects are working as-well.
=> High CPU Usage Fixes

Project-Aurora/Devices/AtmoOrb/AtmoOrbDevice.cs, Project-Aurora/Settings/Configuration.cs, Project-Aurora/Settings/Control_Settings.xaml, Project-Aurora/Settings/Control_Settings.xaml.cs
- Added AtmoOrb send delay in settings (defaults to 50ms).
- AtmoOrb only connects if user has setting enabled.
Should help reduce the network load mentioned in issues #342
=> AtmoOrb - improvements

Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml, Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml.cs, Project-Aurora/Settings/Layers/InteractiveLayerHandler.cs
Added the option to assign which keys are gonna fade.
=> Added more options to Key Fade effect

Project-Aurora/Project-Aurora/Profiles/CSGO/GSI/Nodes/RoundNode.cs
- Spelling corrections in RoundNode comments
=> Update RoundNode.cs with spelling corrections

Project-Aurora/Project-Aurora/Settings/Layers/Control_EqualizerLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_EqualizerLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/EqualizerLayerHandler.cs
Implements #665 
I suggested it and then I thought I'd just try to implement it, so here goes nothing.
Its just an additional checkbox in the equalizer settings and the backing property, also an additional variable in the render method of the equalizer.
=> Added scaling with System sound as a checkbox to the Equalizer settings

Project-Aurora/Project-Aurora/Devices/SteelSeries/GameSenseSDK.cs
This builds upon #645.
* Fixes malformed JSON in the keyboard payload. This fixes M800 support.
* Changes to GameSense handlers. Instead of different handlers for each type of event, use one handler for all color events. Works better with the SteelSeries Engine frontend.
Improves on #162.
=> Update SteelSeries GameSense support

Project-Aurora/Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_InteractiveLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/InteractiveLayerHandler.cs
Implements #623 
Hope everything is okay with the code style.
=> Added Interactive Effect option to start progress of effect when key is released

Project-Aurora/Project-Aurora/Utils/KeyUtils.cs
- Fixed #444 
N/A
N/A
Well, I don't know why the normal keys are the extended ones...
=> Fixed broken Numpad-Keys when Numlock not active

Project-Aurora/Project-Aurora/Controls/Control_VariableIItem.xaml.cs
- Fixed #684 
N/A
N/A
You are to fast for me, otherwise this would be in the other PR 🐕
=> Fixed animator crash

Project-Aurora/Project-Aurora/InputEventsSubscriptions.cs, Project-Aurora/Project-Aurora/Settings/KeyRecorder.cs, Project-Aurora/Project-Aurora/Settings/Layers/InteractiveLayerHandler.cs, Project-Aurora/Project-Aurora/Utils/KeyUtils.cs
- Fixed #311
N/A
- Somebody should look also into #145 (Same issue , but in ShortcutAssistantLayer), if someone does it before me, this PR can be accepted. If not, I include the fix into this.
=> [Interactive Layer] Fixed LControl lighting up, when Alt GR is pressed

Project-Aurora/Project-Aurora/EffectsEngine/ColorSpectrum.cs, Project-Aurora/Project-Aurora/EffectsEngine/EffectLayer.cs
- Fix: ```ColorSpectrum.ToLinearGradient``` ignored shift value.
- Fix typo in ```ColorSpectrum.Shift```.
- Fix: piece of last gradient color in PercentEffect sometimes was also drawn in the beginning due to float error.
=> Small fixes in ColorSpectrum and PercentEffect.

Project-Aurora/Project-Aurora/Profiles/Aurora Wrapper/GameEvent_Aurora_Wrapper.cs
Fixes #762 Bug from PR #335 as described in said Issue
=> Fixes wrong colour when using HSV

Project-Aurora/Project-Aurora/Settings/Layers/EqualizerLayerHandler.cs
=> Fixed Visualizer layer freezing after NAudio exception

Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterDevice.cs, Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterSDK.cs
Fixes issue mentioned in comments of #802 where keyboard lights weren't working for any Masterkeys keyboards except Pro L.
=> Fixed issue where only Masterkeys Pro L worked

Project-Aurora/Project-Aurora/Profiles/DyingLight/DyingLightProfile.cs
This should cover most if not all the usable keys in-game.
=> Improved Default Dying Light Profile

Project-Aurora/Project-Aurora/Controls/KeyBindList.xaml, Project-Aurora/Project-Aurora/Controls/KeyBindList.xaml.cs, Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Layers/Control_ToggleKeyLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_ToggleKeyLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/ToggleKeyLayerHandler.cs
Added a key toggle layer (based on the suggestion from #1017) that toggles a sequence on/off when one or more key combinations are pressed.
In the above example, when Ctrl + F8 are pressed, the red keys change to green. When Ctrl + F8 is pressed again, they change back to red.
=> Added a Key Toggle Layer

index.html
- Add links to all supported games
=> Add links to supported games

Project-Aurora/Project-Aurora/Devices/Roccat/RoccatDevice.cs
Change "DeviceKeys.Peripheral" to "DeviceKeys.Peripheral_Logo", bacause I want to use DS4 and Roccat mice at once and most other implementation use "DeviceKeys.Peripheral_Logo".
=> Change Key

Project-Aurora/Project-Aurora/Devices/Dualshock4/Dualshock4Device.cs
update DS4 options "Set restore color for your DS4 Controller"
=> update DS4 options

Project-Aurora/Aurora-RazerLEDWrapper/dllmain.cpp
Chroma Integrated Games
- Adds Chroma Link Effect
- Fixes Custom Key not retrieving RGB values in HandleKeyboardMethod
-
=> Updated Razer wrapper to fix custom keys effect

Project-Aurora/Project-Aurora/Devices/SteelSeriesHID/SteelSeriesHID.cs
- Fixes a issue with SS HID. Now SS HID is working.
- Adds Rival 110, Rival 300 HP Omen and Rival 300 Fallout 4 support.
- To-do: Add Rival 600/700 support.
=> Update to SSHID

Project-Aurora/Project-Aurora/Profiles/GameState.cs
Added `MicrophoneLevel` property that returns the detected volume from default microphone. Designed for use with the percent layer, it returns a value between 0 - 100 though if your mic is not very sensitive a lower value could be used to compensate.
=> Added MicrophoneLevel property to LocalPCInfo

Project-Aurora/Project-Aurora/Profiles/GameState.cs
You can use software like [MicMute](https://sourceforge.net/projects/micmute/) to Mute your Mic in the Windows Settings.
- Add MicLevel If not Muted
- Add Mic Muted
- 
- 
-
=>  Add MicLevel If not Muted and Mic Muted 

Project-Aurora/Project-Aurora/Profiles/Application.cs, Project-Aurora/Project-Aurora/Settings/Control_ProfileManager.xaml.cs
- Support for both old and new .cueprofiles as well as .cuefolders
- Imported Profile will have its name as defined in XML rather than default Profile 1, 2 etc.
- Importing .cuefolder will import multiple profiles as defined there
- Fixed the bug for some cue profiles not fetching the required effect and therefore not importing its layer if the effect name was not defined within XML
- Code Optimization/Review
-
=> Added support for importing Corsair Profile and Folder

Project-Aurora/Project-Aurora/Devices/Roccat/RoccatInstallInstructions.xaml.cs
Updated Roccat talk fx download link, because they removed the download site.
=> updated roccat talk fx download

Project-Aurora/Aurora-LogiLEDWrapper/dllmain.cpp, Project-Aurora/Project-Aurora/Profiles/Aurora Wrapper/GameEvent_Aurora_Wrapper.cs
Updated the wrapper with new commands which were earlier missing from wrapper. It should now support more apps such as -
http://dynftw.tk/spectrogram/downloads.php
=> Updated Logitech Wrapper with new commands

Project-Aurora/Project-Aurora/Devices/Logitech/LogitechDevice.cs, Project-Aurora/Project-Aurora/Devices/Logitech/LogitechGSDK.cs, Project-Aurora/Project-Aurora/Settings/Configuration.cs, Project-Aurora/Project-Aurora/Settings/KeyboardLayoutManager.cs, Project-Aurora/Project-Aurora/kb_layouts/logitech_g213.json
**List any issues that this PR fixes:** fixes #205
- Adds G213 support but this time it is working.
- None.
=> G213 Support

Installer/installer.iss, Installer/readme.md, Project-Aurora/Project-Aurora/Devices/Device.cs
- Fixed vc redist checks in installer, added parameter support to installer and uninstaller (check readme.md in "Installer" directory for list of parameters).
- Installer now uninstalls old versions of aurora using "/silent", "/keepstartuptask" and "/keepsettings" parameters.
- Fixed most unnoticed typo in Devices.cs
- None.
=> Better installer/uninstaller

Installer/installer.iss
**List any issues that this PR fixes:** None
- Adds another confirmation to settings removal in uninstaller.
- None yet.
=> Updated uninstaller, added more confirmations to uninstaller

Project-Aurora/Project-Aurora/ConfigUI.xaml.cs
Fixes bug that causes Aurora to not shutdown properly.
=> Possible fix to the shutdown bug

Project-Aurora/Project-Aurora/Settings/Control_ProfileControlPresenter.xaml
=> Made Profile Keybind Box wider

Project-Aurora/Project-Aurora/Profiles/Desktop/Event_Idle.cs, Project-Aurora/Project-Aurora/Settings/Configuration.cs
As I [sad](https://github.com/antonpup/Aurora/issues/277) I was going to fix stuttering in rainfall animation. Here is new implementation. I've added it as new "Rain Fall Smooth" animation.
=> RainFall Smooth implementation

Project-Aurora/Project-Aurora/Devices/UnifiedHID/AsusPugio.cs, Project-Aurora/Project-Aurora/Devices/UnifiedHID/RivalMouses.cs, Project-Aurora/Project-Aurora/Devices/UnifiedHID/RoccatVulcan.cs, Project-Aurora/Project-Aurora/Devices/UnifiedHID/UnifiedHID.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj
**List any issues that this PR fixes:** None
- Adds pretty name field for unifiedbase classes.
- Moved implementations to different files.
- Used reflection to detect new unifiedbase classes and add them to AllDevices of UnifiedHID automatically.
- None ATM.
=> UnifiedHID Improvised

Project-Aurora/Project-Aurora/Settings/Layers/Control_RazerLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_RazerLayer.xaml.cs
* Fixes exception when adding key clone entry when an entry with the same destination key already exists
* Adds stretching behavior to key clone list to make it easier to see more entries
* Adds ability to select & delete multiple key clone entries at once
* Adds automatic deselect of destination key after adding a new entry
=> Minor fixes and changes to razer layer

Project-Aurora/Project-Aurora/Profiles/Slime Rancher/SlimeRancherProfile.cs
It was causing log spam and of course Nimble Valley color was not working
=> Fix Typo in SR Profile

Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/packages.config
Updated Asus RGB.NET Nuget to 0.1.26
=> Updated Asus RGB.NET Nuget to 0.1.26

Project-Aurora/Project-Aurora/Settings/Layers/GlitchLayerHandler.cs
- enable keysellection
- if the keylist is used only redraw them instead of all keys
**Help needed?:**
- I do not know how to get a list of keys inside the freestyle so I will keep the old methode for that for now.
Please tell me if you know how to do it.
=> Fix glitch layer Sequence + performance improvement

Project-Aurora/Project-Aurora/Profiles/GTA5/GSI/GameState_GTA5.cs
=> Updated GTA5 colors

Project-Aurora/Project-Aurora/Profiles/LightingStateManager.cs, Project-Aurora/Project-Aurora/Project-Aurora.csproj, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Boolean_GameState.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Boolean_NumericChangeDetector.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Boolean_PeripheralInput.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Boolean_ProcessRunning.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Boolean_TrueExtender.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Control_BooleanGSIEnum.xaml, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Boolean/Control_BooleanGSIEnum.xaml.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Control_TimeAndUnit.xaml, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Control_TimeAndUnit.xaml.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Number/Number_Maths.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Logic/Number/Number_PeripheralInput.cs, Project-Aurora/Project-Aurora/Utils/ActiveProcessMonitor.cs, Project-Aurora/Project-Aurora/Utils/FrameworkElementUtils.cs, Project-Aurora/Project-Aurora/Utils/GameStateUtils.cs, Project-Aurora/Project-Aurora/Utils/JSONUtils.cs
This PR adds an `IEvaluatable<bool>` that determines if the specified enum game state parameter matches the given value.
Once the user has chosen a game state, the available enum values then populate the second dropdown. Note that if the enum value has a description (using the `DescriptionAttribute`), this will be the value displayed in the dropdown.
=> Enum Comparison Evaluatable

Project-Aurora/Project-Aurora/Profiles/LeagueOfLegends/Control_LoL.xaml.cs
I made this PR a long time ago and closed because i was told it wasn't working. After testing it myself i was able to verify that it IS indeed working. Also it's such a simple fix that there' really no point in not merging it.
=> Updated League of Legends patcher with new game path

Project-Aurora/Project-Aurora/Settings/Layers/Control_AnimationLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Overrides/Control_OverridesEditor.xaml.cs
- Update Guide buttons to new Guide
- 
- 
**Additional ideas:**
- Maybe add an first time aurora openend screen to informing about the Guide.
- Add a more obvious button into the Settings?
-
=> Update Guide buttons to new Guide

Project-Aurora/Project-Aurora/Profiles/Minecraft/MinecraftApplication.cs
**List any issues that this PR fixes:** Fixes #1910 
- Add support for title detection when using Fabric
- N/A
=> Improve Minecraft version parsing to support Fabric

Project-Aurora/Project-Aurora/Controls/Control_DeviceItem.xaml.cs, Project-Aurora/Project-Aurora/Devices/Ducky/DuckyDevice.cs
Fixes my stupidity XD
- Fix a crash where no ducky device is connected
=> Fix crash if no ducky device is connected.

Project-Aurora/Project-Aurora/NLog.config
also capped max log size at 10mb per file, and 6 files
=> Repeated log lines will now only be logged every 30 seconds

Project-Aurora/Project-Aurora/EffectsEngine/EffectLayer.cs, Project-Aurora/Project-Aurora/Settings/LayerEffectConfig.cs, Project-Aurora/Project-Aurora/Settings/Layers/Control_GradientLayer.xaml, Project-Aurora/Project-Aurora/Settings/Layers/Control_GradientLayer.xaml.cs, Project-Aurora/Project-Aurora/Settings/Layers/GradientLayerHandler.cs
Changeable wave length in the gradient Layer
If Wave Size 0, then behavior like gradient fill Layer
Fixes #441, fixes #797, fixes #1021, and fixes #1667
=> Wave animation in gradient layer

Project-Aurora/Project-Aurora/Profiles/GameState.cs, Project-Aurora/Project-Aurora/Utils/HardwareMonitor.cs
adds upload and download speed counters to the NET localpcinfo node.
=> Added upload and download speed counters

Project-Aurora/Project-Aurora/EffectsEngine/EffectLayer.cs, Project-Aurora/Project-Aurora/Settings/Layers/GradientLayerHandler.cs
=> Fix for gradient layer default behavior change

Project-Aurora/Project-Aurora/Devices/Ducky/DuckyDevice.cs
=> No ducky Device exception

Project-Aurora/Project-Aurora/Profiles/Witcher3/GSI/Nodes/Player.cs, Project-Aurora/Project-Aurora/Profiles/Witcher3/GameEvent_Witcher3.cs, Project-Aurora/Project-Aurora/Profiles/Witcher3/Layers/Witcher3BackgroundLayerHandler.cs, Project-Aurora/Project-Aurora/Settings/Control_LayerControlPresenter.xaml.cs
=> fixed reset layer button and simplified witcher 3 update code

Project-Aurora/Project-Aurora/Devices/Asus/AsusDevice.cs, Project-Aurora/Project-Aurora/Devices/Asus/AsusHandler.cs, Project-Aurora/Project-Aurora/Devices/Asus/AsusSyncClaymoreDevice.cs, Project-Aurora/Project-Aurora/Devices/Asus/AuraSyncDevice.cs, Project-Aurora/Project-Aurora/Devices/Asus/AuraSyncKeyboardDevice.cs
- Fixed stopping asus devices
- Added option to disable keyboard / mice within the aurora UI
=> Asus fix 00

Project-Aurora/Project-Aurora/Devices/Asus/AuraSyncKeyboardDevice.cs, Project-Aurora/Project-Aurora/Devices/Asus/Config/AsusConfigWindow.xaml, Project-Aurora/Project-Aurora/Devices/Asus/Config/AsusConfigWindow.xaml.cs
- Asus Key Configuration Window fixes, UI changes
- Asus Key Configuration Window Test button now successfully stops the previous light blinking
- Asus Key Configuration Window features
- Set all to none
- Set all to Peripheral_logo
=> ASUS Fixes 01

Project-Aurora/Project-Aurora/Profiles/Discord/GSI/Nodes/UserNode.cs
- Add `being_called` value - It's present in BD plugin, but it wasn't working properly... it will soon...
- Also triggers if user is the one initiating the call (cannot filter that so I guess it's fine)
- Needs Discord plugin update so it'll work properly (tested, working fine with issue above - will PR in Discord-GSI plugin repo)
=> Add `being_called` value

Project-Aurora/Project-Aurora/Settings/Layers/AmbilightLayerHandler.cs
=> fixed ambilight brightness being 0 by default
